spring:
  devtools:
    restart:
      additional-exclude: src/main/java
      exclude: templates/**
  freemarker:
    cache: false
  datasource:
    username: root
    password: ming527669
    url: jdbc:mysql://localhost:3306/bookstore?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

